program: train_sweep.py 
hyperbad: 
  min_iter: 5
  max_iter: 10
method: bayes #"random" --> Random search

metric: 
    name: ptl/val_accuracy_1
    goal: maximize

parameters: 
   
    epochs: 
        distribution: int_uniform
        min: 45
        max: 70
    lr: 
        # log uniform distribution between exp(min) and exp(max)
        distribution: log_uniform
        min : -9.21 # exp(-9.21) = 1e-5
        max : -2.00    # exp(-2.00) = 0.14e-1
    
    weight_decay: 
       # log uniform distribution between exp(min) and exp(max)
        distribution: log_uniform
        min : -12.21 # exp(-12.21) = 5e-6
        max : -9.21    # exp(-9.21) = 0.14e-4
    lr_scheduler: 
        values: ["step", "reduce"]
    optim_type: 
        values: ["sgd", "adam", "adamw"]